### ISSUE TITLE
Multiple test suite failures

### ISSUE THREAD

**Issue by peti** [alphaHeavy/lzma-conduit#5] opened 2014-12-12 18:20 UTC
The test suite of version 1.1.1 failed with the following error on Linux/i686 (but not Linux/x86_64):

    Test suite lzma-test: RUNNING...
    Compress:
      compressAndDiscard: [OK, passed 100 tests]
      compressAndCheckLength: [OK, passed 100 tests]
    Decompress:
      decompressRandom: [OK, passed 1 tests]
      decompressCorrupt: [OK, passed 1 tests]
    Chained:
      chain: [Failed]
    *** Failed! Exception: 'user error (lzma_auto_decoder failed: Invalid or unsupported options)' (after 1 test): 
    (used seed -463359518)
      compressThenDecompress: [Failed]
    *** Failed! Exception: 'user error (lzma_auto_decoder failed: Invalid or unsupported options)' (after 1 test): 
    (used seed -1226724653)

             Properties  Total      
     Passed  4           4          
     Failed  2           2          
     Total   6           6          
    Test suite lzma-test: FAIL

A complete build log is available at http://hydra.nixos.org/build/17776876/nixlog/1/raw.

**Comment by peti** [comment] 2015-01-14 10:32
Ping?

**Comment by peti** [comment] 2015-08-06 11:34
Now the tests fail on Linux/x86_64 as well: http://hydra.cryp.to/build/1045852/log/raw.

**Comment by sseveran** [comment] 2015-08-10 02:56
Can you be more specific? Tests work fine in our Centos 7 environments.

Test suite lzma-test: RUNNING...
Compress:
  compressAndDiscard: [OK, passed 100 tests]
  compressAndCheckLength: [OK, passed 100 tests]
Decompress:
  decompressRandom: [OK, passed 1 tests]
  decompressCorrupt: [OK, passed 1 tests]
Chained:
  chain: [OK, passed 100 tests]
  compressThenDecompress: [OK, passed 100 tests]

         Properties  Total
 Passed  6           6
 Failed  0           0
 Total   6           6
Test suite lzma-test: PASS
Test suite logged to: dist/test/lzma-conduit-1.1.3-lzma-test.log

**Comment by peti** [comment] 2015-08-10 09:10
What kind of specificity is missing? I believe the build logs contain every information you could possibly need.

**Comment by sseveran** [comment] 2015-08-11 18:00
If the test failure is deterministic for NixOS then it would seem to me to be a NixOS issue. Previously tests passed and since the package has not changed I would suspect that the failure is do to a change in NixOS. Tests pass on other platforms including LTS Haskell and our production gentoo and centos environments. If the nix team would like to contribute a patch to fix the NixOS specific issues that would be great. Alternatively if you would like us to look into it then please provide an exact vagrant image and instructions on how to reproduce the failure.

**Comment by peti** [comment] 2015-08-11 18:09
It's highly unlikely that "NixOS" has any effect on the test. What might make a difference, though, is the version of the underlying LZMA implementation that's used for the test. We use `xz-5.2.1`. Do you use the same version?

**Comment by juhp** [comment] 2015-08-12 03:31
With lzma-conduit-1.1.3 I am seeing a test failure for the Stackage Nightly build:

```
Test suite lzma-test: RUNNING...
Compress:
  compressAndDiscard: [OK, passed 100 tests]
  compressAndCheckLength: [Failed]
*** Failed! Assertion failed (after 4 tests): 
""
(used seed 3104050624236268578)
Decompress:
  decompressRandom: [OK, passed 1 tests]
  decompressCorrupt: [OK, passed 1 tests]
Chained:
  chain: [OK, passed 100 tests]
  compressThenDecompress: [OK, passed 100 tests]

         Properties  Total      
 Passed  5           5          
 Failed  1           1          
 Total   6           6          
Test suite lzma-test: FAIL
```

I can open a separate issue if you prefer.

**Comment by sseveran** [comment] 2015-08-12 03:43
I will leave it up to @NathanHowell as to what he wants to do.

**Comment by peti** [comment] 2015-08-12 11:24
Yeah, well, since nothing has happened with regard to this issue for the last 8 months, I won't be holding my breath expecting a fix. It looks to me like this package is effectively unmaintained and shouldn't be used anymore (unless one is willing to maintain it themselves).

**Comment by NathanHowell** [comment] 2015-08-12 14:25
Looks like this is due to poor random data generation on the host computer and/or an improvement in liblzma's compression ratio of random data (unlikely). I'll relax the test, since it is not an issue with this library.

If you have continued issues, please consider making it easy for developers to fix bugs on little used architectures and distros.

**Comment by NathanHowell** [comment] 2015-08-12 14:37
I've opened #7 for the length test failure, and I'll close this for now since I have no reasonable way to reproduce the original issue or verify it still happens with newer versions of xz-utils. Please reopen this ticket if you're still experiencing failures on i686.

**Closed by NathanHowell** 2015-08-12 14:37 UTC
